"""Migracion de tablas

Revision ID: 44f91de43f64
Revises: 
Create Date: 2025-09-19 21:44:02.767818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f91de43f64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('oauth_access_token', sa.Text(), nullable=False),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=False),
    sa.Column('ultima_sesion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_fecha_actualizacion'), 'usuario', ['fecha_actualizacion'], unique=False)
    op.create_index(op.f('ix_usuario_fecha_creacion'), 'usuario', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    op.create_table('remitente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_correo', sa.Text(), nullable=False),
    sa.Column('nombre_remitente', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_remitente_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remitente'))
    )
    op.create_index(op.f('ix_remitente_fecha_actualizacion'), 'remitente', ['fecha_actualizacion'], unique=False)
    op.create_index(op.f('ix_remitente_fecha_creacion'), 'remitente', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_remitente_nombre_correo'), 'remitente', ['nombre_correo'], unique=False)
    op.create_index(op.f('ix_remitente_nombre_remitente'), 'remitente', ['nombre_remitente'], unique=False)
    op.create_index(op.f('ix_remitente_usuario_id'), 'remitente', ['usuario_id'], unique=False)
    op.create_table('email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora_correo', sa.DateTime(), nullable=False),
    sa.Column('email_id', sa.Text(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.Text(), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('respuesta_ia', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('LEIDO', name='estadoemailenum'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['remitente.id'], name=op.f('fk_email_destinatario_id_remitente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email')),
    sa.UniqueConstraint('email_id', name=op.f('uq_email_email_id'))
    )
    op.create_index(op.f('ix_email_fecha_actualizacion'), 'email', ['fecha_actualizacion'], unique=False)
    op.create_index(op.f('ix_email_fecha_creacion'), 'email', ['fecha_creacion'], unique=False)
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['remitente_id'], ['remitente.id'], name=op.f('fk_prompt_remitente_id_remitente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt')),
    sa.UniqueConstraint('remitente_id', name=op.f('uq_prompt_remitente_id'))
    )
    op.create_index(op.f('ix_prompt_fecha_actualizacion'), 'prompt', ['fecha_actualizacion'], unique=False)
    op.create_table('envio_correo_docente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], name=op.f('fk_envio_correo_docente_email_id_email')),
    sa.ForeignKeyConstraint(['remitente_id'], ['remitente.id'], name=op.f('fk_envio_correo_docente_remitente_id_remitente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_envio_correo_docente'))
    )
    op.create_index(op.f('ix_envio_correo_docente_fecha_actualizacion'), 'envio_correo_docente', ['fecha_actualizacion'], unique=False)
    op.create_index(op.f('ix_envio_correo_docente_fecha_creacion'), 'envio_correo_docente', ['fecha_creacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envio_correo_docente_fecha_creacion'), table_name='envio_correo_docente')
    op.drop_index(op.f('ix_envio_correo_docente_fecha_actualizacion'), table_name='envio_correo_docente')
    op.drop_table('envio_correo_docente')
    op.drop_index(op.f('ix_prompt_fecha_actualizacion'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_email_fecha_creacion'), table_name='email')
    op.drop_index(op.f('ix_email_fecha_actualizacion'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_remitente_usuario_id'), table_name='remitente')
    op.drop_index(op.f('ix_remitente_nombre_remitente'), table_name='remitente')
    op.drop_index(op.f('ix_remitente_nombre_correo'), table_name='remitente')
    op.drop_index(op.f('ix_remitente_fecha_creacion'), table_name='remitente')
    op.drop_index(op.f('ix_remitente_fecha_actualizacion'), table_name='remitente')
    op.drop_table('remitente')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_fecha_creacion'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_fecha_actualizacion'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
