"""Se agrega nueva clase GmailToken y relacion con clase Usuario

Revision ID: ac4fbd1eae8e
Revises: 44f91de43f64
Create Date: 2025-09-22 01:19:01.940217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4fbd1eae8e'
down_revision: Union[str, Sequence[str], None] = '44f91de43f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_token_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token'))
    )
    op.create_index(op.f('ix_token_fecha_actualizacion'), 'token', ['fecha_actualizacion'], unique=False)
    op.create_index(op.f('ix_token_fecha_creacion'), 'token', ['fecha_creacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_fecha_creacion'), table_name='token')
    op.drop_index(op.f('ix_token_fecha_actualizacion'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
