"""Modificacion de modelos de datos

Revision ID: e25593e77b5c
Revises: ac4fbd1eae8e
Create Date: 2025-10-07 22:55:27.436601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e25593e77b5c'
down_revision: Union[str, Sequence[str], None] = 'ac4fbd1eae8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envio_correo_docente_fecha_actualizacion'), table_name='envio_correo_docente')
    op.drop_index(op.f('ix_envio_correo_docente_fecha_creacion'), table_name='envio_correo_docente')
    op.drop_table('envio_correo_docente')
    op.add_column('email', sa.Column('cuerpo_snippet', sa.Text(), nullable=False))
    op.add_column('email', sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('email', 'fecha_hora_correo',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_email_destinatario_id_remitente'), 'email', type_='foreignkey')
    op.create_foreign_key(op.f('fk_email_remitente_id_remitente'), 'email', 'remitente', ['remitente_id'], ['id'])
    op.create_foreign_key(op.f('fk_email_destinatario_id_usuario'), 'email', 'usuario', ['destinatario_id'], ['id'])
    op.drop_column('email', 'cuerpo')
    op.drop_column('email', 'estado')
    op.add_column('prompt', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_prompt_remitente_id'), 'prompt', type_='unique')
    op.drop_constraint(op.f('fk_prompt_remitente_id_remitente'), 'prompt', type_='foreignkey')
    op.create_foreign_key(op.f('fk_prompt_usuario_id_usuario'), 'prompt', 'usuario', ['usuario_id'], ['id'])
    op.drop_column('prompt', 'remitente_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('remitente_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_prompt_usuario_id_usuario'), 'prompt', type_='foreignkey')
    op.create_foreign_key(op.f('fk_prompt_remitente_id_remitente'), 'prompt', 'remitente', ['remitente_id'], ['id'])
    op.create_unique_constraint(op.f('uq_prompt_remitente_id'), 'prompt', ['remitente_id'])
    op.drop_column('prompt', 'usuario_id')
    op.add_column('email', sa.Column('estado', postgresql.ENUM('LEIDO', name='estadoemailenum'), autoincrement=False, nullable=True))
    op.add_column('email', sa.Column('cuerpo', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_email_destinatario_id_usuario'), 'email', type_='foreignkey')
    op.drop_constraint(op.f('fk_email_remitente_id_remitente'), 'email', type_='foreignkey')
    op.create_foreign_key(op.f('fk_email_destinatario_id_remitente'), 'email', 'remitente', ['destinatario_id'], ['id'])
    op.alter_column('email', 'fecha_hora_correo',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('email', 'fecha_envio')
    op.drop_column('email', 'cuerpo_snippet')
    op.create_table('envio_correo_docente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remitente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], name=op.f('fk_envio_correo_docente_email_id_email')),
    sa.ForeignKeyConstraint(['remitente_id'], ['remitente.id'], name=op.f('fk_envio_correo_docente_remitente_id_remitente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_envio_correo_docente'))
    )
    op.create_index(op.f('ix_envio_correo_docente_fecha_creacion'), 'envio_correo_docente', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_envio_correo_docente_fecha_actualizacion'), 'envio_correo_docente', ['fecha_actualizacion'], unique=False)
    # ### end Alembic commands ###
