"""Agrega clase usuario

Revision ID: fdc52919679b
Revises: 
Create Date: 2025-09-19 15:28:52.863748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc52919679b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('oauth_access_token', sa.String(length=255), nullable=False),
    sa.Column('oauth_refresh_token', sa.String(length=512), nullable=False),
    sa.Column('ultima_sesion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_fecha_actualizacion'), 'usuarios', ['fecha_actualizacion'], unique=False)
    op.create_index(op.f('ix_usuarios_fecha_creacion'), 'usuarios', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_index(op.f('ix_usuarios_oauth_access_token'), 'usuarios', ['oauth_access_token'], unique=False)
    op.create_index(op.f('ix_usuarios_oauth_refresh_token'), 'usuarios', ['oauth_refresh_token'], unique=False)
    op.create_index(op.f('ix_usuarios_ultima_sesion'), 'usuarios', ['ultima_sesion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_ultima_sesion'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_oauth_refresh_token'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_oauth_access_token'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fecha_creacion'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fecha_actualizacion'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
